version: '3'
services:
  nestjs-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nestjs-app
    environment:
      - MONGO_URI=mongodb+srv://eco_book:eco123@cluster0.mongodb.net/yourDatabase?retryWrites=true&w=majority
    depends_on:
      - nginx
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./certs:/etc/nginx/certs
    ports:
      - 80:80
      - 443:443
    depends_on:
      - nestjs-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
